---
apps/v1
kind: Deployment
metadata:
  name: contrail-zookeeper
  namespace: {{ .Values.global.namespace }}
  labels:
    app: contrail-zookeeper
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: contrail-zookeeper
  template:
    metadata:
      labels:
        app: contrail-zookeeper
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      hostNetwork: true
      serviceAccountName: contrail-service-account
      initContainers:
      - name: contrail-k8s-init
        image: {{ .Values.global.containerRegistry }}/contrail-k8s-init-container:{{ .Values.global.containerTag }}
        command: ["/contrail-k8s-init","contrail-zookeeper"]
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: wait-for-vhost0
        image: busybox
        command: ["sh","-c","until ifconfig vhost0 > /dev/null 2>&1; do sleep 1;echo waiting for vhost0 ;done;echo vhost0 is alive"]
      containers:
      - name: zookeeper
        image: "{{ .Values.global.containerRegistry }}/contrail-external-zookeeper:{{ .Values.global.containerTag }}"
        imagePullPolicy: ""
        env:
        - name: ZOOKEEPER_PORT
          value: "2181"
        - name: ZOOKEEPER_PORTS
          value: "2888:3888"
        - name: NODE_TYPE
          value: config-database
        - name: ZOOKEEPER_NODES
          valueFrom:
            configMapKeyRef:
              name: contrailcontrollernodesv1
              key: CONTROLLER_NODES
        volumeMounts:
        - mountPath: /var/lib/zookeeper
          name: zookeeper-data
        - mountPath: /var/log/zookeeper
          name: zookeeper-logs
      volumes:
      - name: zookeeper-data
        hostPath:
          path: /var/lib/contrail/zookeeper
      - name: zookeeper-logs
        hostPath:
          path: /var/log/contrail/zookeeper
